### PR TITLE
Bug fixes & Switch Alpine to Debian

### PR DESCRIPTION
**Pull request by ichicho**
When executing `nanaco_auto_fill.py` on my Ubuntu 22.04,

> Traceback (most recent call last):
>   File "/home/ichicho/code/nagias/nanaco_auto_fill.py", line 173, in <module>
>     nanaco.main()
>   File "/home/ichicho/code/nagias/nanaco_auto_fill.py", line 125, in main
>     self.__go_to_register_confirm_page()
>   File "/home/ichicho/code/nagias/nanaco_auto_fill.py", line 108, in __go_to_register_confirm_page
>     self.__driver.find_element_by_id('submit-button').click()
>   File "/home/ichicho/code/env/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 89, in click
>     self._execute(Command.CLICK_ELEMENT)
>   File "/home/ichicho/code/env/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 773, in _execute
>     return self._parent.execute(command, params)
>   File "/home/ichicho/code/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
>     self.error_handler.check_response(response)
>   File "/home/ichicho/code/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementNotInteractableException: Message: Element \<input id="submit-button" src="/img/btn_confirm.gif" type="image"\> could not be scrolled into view
> Stacktrace:
> WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
> ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.jsm:293:5
> webdriverClickElement@chrome://remote/content/marionette/interaction.js:156:11
> interaction.clickElement@chrome://remote/content/marionette/interaction.js:125:11
> clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:203:24
> receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:91:31

reveals randomly. It seems like that
https://github.com/kadoyau/nagias/blob/61d90e52cff11b280ae3e65c3e64f383460daac5/nanaco_auto_fill.py#L24-L25
fail to prevent
> selenium.common.exceptions.ElementNotInteractableException: Message: Element \<input id="submit-button" src="/img/btn_confirm.gif" type="image"\> could not be scrolled into view

from happening. 
According to [this post](https://stackoverflow.com/a/56361554), I switched to use
https://github.com/ichicho/nagias/blob/3794e2b0e8348d7f5779a87b11639de85b3375ba/nanaco_auto_fill.py#L111
instead of 
https://github.com/kadoyau/nagias/blob/61d90e52cff11b280ae3e65c3e64f383460daac5/nanaco_auto_fill.py#L25
and the bug disappeared. Therefore, I deleted 
https://github.com/kadoyau/nagias/blob/61d90e52cff11b280ae3e65c3e64f383460daac5/nanaco_auto_fill.py#L24-L25
and changed all `webdriver.find_element` to `WebDriverWait(webdriver, 3), until()`.

### CODE REVIEW

**Comment by ichicho** [comment]
Besides, there is a strange bug when running current version of  `chromium` that `"#memberNavi02" cannot be found.

> Traceback (most recent call last):
>   File "/home/nagias/nanaco_auto_fill.py", line 173, in <module>
>     nanaco.main()
>   File "/home/nagias/nanaco_auto_fill.py", line 113, in main
>     self.__go_to_agreement_page()
>   File "/home/nagias/nanaco_auto_fill.py", line 92, in __go_to_agreement_page
>     self.__driver.find_element_by_css_selector('#memberNavi02').click()
>   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 597, in find_element_by_css_selector
>     return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
>   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 964, in find_element
>     return self.execute(Command.FIND_ELEMENT, {
>   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#memberNavi02"}
>   (Session info: headless chrome=102.0.5005.61)
 
I failed to debug it but the code works smoothly with `Firefox` installed in `Debian`. Because newer version of `Selenium` needs to be complied to install on `Alpine`, switch to `Debian` is somehow inevitable although the container becomes bigger(518MB).

**Comment by ichicho** [comment]
Finally, usage under Ubuntu Desktop is added.

**Comment by kadoyau** [comment]
Sorry for the delay in my noticing. I'm going to review it. Thank you.

**Comment by kadoyau** [comment]
@ichicho 
I sincerely apologize for my delayed response.
I have carefully gone through your PR and fully comprehend the changes.
I would like to express my gratitude for your contribution to the code. Thank you very much.

**Pull request merged**
